### ISSUE TITLE
Device Major Minor Data Inaccurate

### ISSUE THREAD

**Issue by jrmwooldridge** [vmware/cbsensor-linux-bpf#2]
The device returned appears to may have an alignment problem. This might be due to an offset calculation error from BCC on the `struct super_block` containing the `dev_t` key field. 

Although it does not seem to cause a data truncation issue.

**Comment by kkass** [comment]
The problem here is that the kernel encodes the dev_t before sending to user space.

**Comment by jrmwooldridge** [comment]
Okay great! Then we can "normalize" it then for userspace then 👍
