### ISSUE TITLE
Whether there is more accurate events than security_file_open for hooking file_create

### ISSUE THREAD

**Issue by hz-kelpie** [vmware/cbsensor-linux-bpf#50]
Too many events were triggered

**Comment by jrmwooldridge** [comment]
@hz-kelpie thanks for reporting this. The python example program has plenty of limitations when it comes to data throughput. This project has been migrated to another github repo within the VMware account  and has gone under more drastic changes to where the example python and go versions don't work.

https://github.com/vmware/kernel-event-collector-module/tree/master/bpf_probe

Cheers,
Jeff W
